version: '3.4'

services:
  portfolio:
    image: portfolio
    build:
      context: Portfolio_2
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
